### ISSUE TITLE
Class 'Midnite81\Plivo\MessengingServiceProvider'

### ISSUE THREAD

**Issue by morgothx** [midnite81/plivo#5]
I was following the guide provide on this page and when i run 

`php artisan vendor:publish --provider="Midnite81\Plivo\MessagingServiceProvider"
`

i got 

`[Symfony\Component\Debug\Exception\FatalErrorException]      
  Class 'Midnite81\Plivo\MessengingServiceProvider' not found`

I'm running laravel 5.2 on a custom box

**Comment by midnite81** [comment]
Sorry I didn't see this until now, my notifications don't appear to be working. I'll check into this for you.

**Comment by midnite81** [comment]
Hi @morgothx, I think if you run composer dump-autoload before adding the the class to the providers and aliases in `app.php` and then re-add them and then try that should work. Please let me know if this fixes the issue you were having with it.

**Comment by jab1000** [comment]
I get the same errors even when I try do do a "composer update" and also a "composer dump-autoload" -- before and after updating the app config file.

I am running latest laravel 5.2.38 on php 5.6.22

**Comment by morgothx** [comment]
Hi, sorry i just see the message, and unfortunately i have to use another project because of dead lines.

I will try to replicate the project and the issue on my home and then i will tell you if it work with your suggestion

Thank you

**Comment by midnite81** [comment]
I've been unable to replicate your issue @jab1000, however I'll create a virtual box at the weekend and see if I run into the same issue.

**Comment by midnite81** [comment]
Hi @jab1000, @morgothx. I found the error - it was in the readme. The class name is slightly misspelt. I've updated the docs in commit 8556922 and submitted a new release. You should not get an error using the updated docs.
