### ISSUE TITLE
Enviroment parameter for phone validation rule

### ISSUE THREAD

**Issue by morgothx** [midnite81/plivo#6]
Hi:

I see on Sms.php when using the send method, it calls the validatePhoneNumbers method which receives a $rule parameters with a default value = 'AUTO,US,mobile'.

I'm currently on Colombia so I change the US to CO and it works, but I can't find where to set this value or how can I send it to the method (currently i write the "CO" on the vendor folder in the Sms.php)

Thank you

**Comment by midnite81** [comment]
Hi there, 

Are you sure it is Sms.php from this repository? I've done a search for file on this repository and its dependencies and it doesn't return anything. Please could you specify where Sms.php is located. 

Many thanks

**Comment by morgothx** [comment]
Sorry you are right, i have 2 tabs open, my bad
