### ISSUE TITLE
Call sendMessage function in existing controller

### ISSUE THREAD

**Issue by chadpriddle** [midnite81/plivo#7]
How do I call the send message function in my controller that I already have.

I have this at the top of my controller:
use Midnite81\Plivo\Contracts\Services\Messaging;

I want something like this I think:
function sms() 
{
    Messaging::msg('Hello World!')->to('0123456789')->sendMessage();
}

So when I call my route it will trigger the sms function without using this: sendMessage(Messaging $messaging)

Thanks

**Comment by midnite81** [comment]
As you're accessing it as `Messaging::msg()` etc .. you need to use the Facade rather than the Contract. 

Replace 
`use Midnite81\Plivo\Contracts\Services\Messaging;`
with 
`use Midnite81\Plivo\Facades\Messaging;`

Hope that helps.

**Comment by chadpriddle** [comment]
wow, i cant believe I missed that, thanks!
